from setuptools import setup

setup(
    name="imagiq",
    version="0.0.1.dev0",
    description="ImagiQ python package",
    url="https://github.com/stephenbaek/imagiqfl",
    author="ImagiQ",
    author_email="chlqnrjs@gmail.com",
    packages=["imagiq"],
    python_requires=">=3.8",
    license="Apache License 2.0",
    install_requires=[
        "ipykernel",
        "jupyter",
        "itk",
        "monai==0.4.0",
        "numpy",
        "pandas",
        "pytest",
        "pytest-flake8",
        "pytest-pythonpath",
        "pytest-check",
        "pytest-cov",
        "scikit-learn",
        "sklearn",
        "tqdm",
        "pytorch-ignite",
        "matplotlib",
        "pydicom",
        "medpy",
        "opencv-python",
    ],
    classifiers=[
        "Develpoment Status :: 1 - Planning",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
    ],
)
